---
openapi: 3.0.0
info:
  title: Todolist-challenge
  description: "This is a todoloist developed for Toduba challenge.  \n"
  contact:
    email: silvio.tari@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:3001
  description: Local server
tags:
- name: user
  description: Registration and LogIn
- name: todo
  description: Create, get, modify and delete todos
paths:
  /user/register:
    post:
      tags:
      - user
      summary: Create user
      description: This is the endpoint to create a new user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: Get the newly created user id and bearer token.
  /user/login:
    post:
      tags:
      - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogResponse'
        "400":
          description: Invalid username or password
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: Brypt hash
      xml:
        name: User
    LogResponse:
      type: object
      properties:
        id:
          type: string
        accessToken:
          type: string
          format: JWT
      xml:
        name: LogResponse
